services:
  monie_db:
    image: postgres:17-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - monie-network

  monie_redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - monie-network
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  monie_api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: monie_api
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DEBUG=${DEBUG:-false}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - REDIS_URL=redis://monie_redis:6379
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - monie-network
    depends_on:
      - monie_db
      - monie_redis

  monie_ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8000/api
    env_file:
      - .env
    ports:
      - "3000:80"
    networks:
      - monie-network
    depends_on:
      - monie_api

volumes:
  postgres_data:
  redis_data:

networks:
  monie-network:
    driver: bridge
